project:
  type: website

website:
  title: "Policy Simulation Library Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/PSLmodels
      - icon: twitter
        href: https://twitter.com/PSLmodels
format:
  html:
    theme: cosmo
    css: styles.css



